server:
  port: 8888
  ip: 192.168.1.100
  localIp: 127.0.0.1

# fastdfs服务器配置
fastdfs:
  connect_timeout_in_seconds: 5
  network_timeout_in_seconds: 30
  charset: UTF-8
  http_anti_steal_token: false
  http_tracker_http_port: 80
  tracker_servers: ${server.ip}:22122
  uploadSmallFileUri: http://${server.ip}/
  uploadBigFileUri: http://${server.ip}:8888/fastdfs/applicationToFile?id=

# mysql数据库配置
spring:
  datasource:
    url: jdbc:mysql://${server.localIp}:3306/fastdfs?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 12345678
    driverClassName: com.mysql.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
      enabled: false

## Mybatis配置
mybatis:
  typeAliasesPackage: com.software.yanchang.domain
  mapperLocations: classpath:mapper/*.xml

# 添加日志配置
logging:
  file: ./spring.log
  level:
    com:
      software: DEBUG

# 设置应用服务器下载客户端文件的地址
breakpoint:
  upload:
    dir: /home/one/
# 存放fineUploader上传的文件的临时目录
breakpoint:
  upload:
    dir:
      tmp: /home/one/tmp/
      fin: /home/one/fin/
